# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNPhotoPicker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNPhotoPicker
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNGL', :path => '../node_modules/gl-react-native'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', # needed for debugging
  'RCTAnimation',
  'RCTImage',
  'RCTNetwork',
  'RCTGeolocation',
  'RCTActionSheet',
  'RCTVibration',
  'RCTLinkingIOS',
  'RCTPushNotification',
  'RCTCameraRoll',
  'BatchedBridge',
  # Add any other subspecs you want to use in your project
  ]
  
  target 'RNPhotoPickerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
